# Generated by Django 3.1.7 on 2021-06-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message',
        ),
    ]
