# Generated by Django 3.1.7 on 2021-06-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='messages',
            new_name='message',
        ),
    ]
