# Generated by Django 3.1.7 on 2021-06-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0006_auto_20210611_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='group',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(max_length=100),
        ),
    ]
