# Generated by Django 3.1.7 on 2021-06-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0008_auto_20210611_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messaged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=100)),
                ('date', models.IntegerField()),
                ('month', models.CharField(max_length=15)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
