# Generated by Django 3.1.7 on 2021-06-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0009_auto_20210612_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messagez',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=100)),
                ('date', models.IntegerField()),
                ('month', models.CharField(max_length=15)),
                ('year', models.IntegerField()),
                ('district', models.CharField(max_length=19)),
                ('hospital', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Messaged',
        ),
    ]
