# Generated by Django 3.1.7 on 2021-06-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0010_auto_20210612_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='Messagez',
            new_name='Message',
        ),
        migrations.DeleteModel(
            name='Done',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
