# Generated by Django 3.1.7 on 2021-06-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0011_auto_20210615_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
    ]
